# Generated by Django 5.2.8 on 2025-11-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('tipo_contrato', models.CharField(max_length=50)),
                ('jornada', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_salario', models.CharField(max_length=50)),
                ('salario_basico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('eps', models.CharField(max_length=100)),
                ('fondo_pensiones', models.CharField(max_length=100)),
                ('arl', models.CharField(max_length=100)),
                ('caja_compensacion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empleados/')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nit', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
