# Generated by Django 5.2.8 on 2025-11-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='bonificaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='empleado',
            name='descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horas_extra_diurna',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horas_extra_festiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horas_extra_nocturna',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
