# Generated by Django 5.2.8 on 2025-11-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_empleado_bonificaciones_empleado_descuentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='salario_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
