# Generated by Django 5.2.8 on 2025-11-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_empleado_salario_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
