# Generated by Django 5.2.8 on 2025-11-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_empleado_salario_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='token_recuperacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
