# Generated by Django 5.2.8 on 2025-11-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_empresa_token_expira_empresa_token_recuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.empresa'),
        ),
    ]
